// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="antialiased">
//         <nav className="bg-white border-b border-gray-200 sticky top-0 z-50 h-14">
//           <div className="max-w-4xl mx-auto px-4 h-full flex items-center justify-between">
//             {/* Logo */}
//             <div className="text-xl font-bold tracking-tight text-[#064e3b]">
//               AERON<span className="text-[#d4af37]">RMC</span>
//             </div>
            
//             {/* Simple Icons/Links */}
//             <div className="flex items-center space-x-6">
//               <a href="/dashboard/customer" className="text-sm font-medium hover:text-[#d4af37]">Requests</a>
//               <a href="/dashboard/admin" className="text-sm font-medium hover:text-[#d4af37]">Admin</a>
//               <div className="w-7 h-7 bg-gray-200 rounded-full border border-[#d4af37]" />
//             </div>
//           </div>
//         </nav>
//         <main className="max-w-xl mx-auto py-8 px-4">{children}</main>
//       </body>
//     </html>
//   )
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AERON RMC | Management System",
  description: "Concrete Ordering and Quotation System",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f8f9fa]`}>
        {/* Only keep things here that should be on EVERY page (like fonts/providers) */}
        {children}
      </body>
    </html>
  );
}