# Generated by Django 5.2.13 on 2026-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='volume_m3',
        ),
        migrations.AlterField(
            model_name='order',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
