# Generated by Django 5.2.13 on 2026-04-22 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_volume_m3_alter_order_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Re-inspection', 'For Re-inspection')], max_length=20)),
                ('remarks', models.TextField()),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_report', to='core.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
