# Generated by Django 5.2.13 on 2026-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quotation_created_at_quotation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_term',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('Terms', 'Credit Terms'), ('Advance', 'Full Advance Payment'), ('DP', 'Percentage Downpayment')], default='COD', max_length=20, null=True),
        ),
    ]
