# Generated by Django 5.2.13 on 2026-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='revision_number',
            field=models.IntegerField(default=0),
        ),
    ]
